# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HeartMonitor' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HeartMonitor
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'GoogleSignIn'
  pod 'FLAnimatedImage'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Alamofire', '~> 4.7.3'
  pod 'Charts'
  pod 'ChartsRealm'
end
